name: Nodejs                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  sast_njscan:
    runs-on: ubuntu-20.04                     # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v4
      
      - name: install njscan and libsast
      - run: pip3 install njsscan==0.3.4 libsast
      
      - name: scan the project
      - run: njsscan --json -o output.json .
        continue-on-error: true
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: output.json
          path: output.json
        if: always()
          
    
