name: Nodejs                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  sast_njscan:
    runs-on: python-latest                     # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v4

      - run: pip3 install njsscan==0.3.4 libsast
      - run: njsscan --json -o output.json .
        continue-on-error: true
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: njscan
          path: output.json 
        if: always()



    
