name: Nodejs                                  # workflow name

on:
  push:                                       
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  sast_njscan:
    runs-on: ubuntu-20.04                     # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v4
      
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
         args: '. --json -o output.json'
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: njscan
          path: output.json 
        if: always()

    
